name: 'Replace Vercel DNS Record'
description: 'Replace a Vercel DNS record by adding one record and deleting all others'
inputs:
  domain:
    description: 'The vercel domain'
    required: true
  subdomain:
    description: 'The vercel subdomain to replace records for'
    required: true
  record-type:
    description: 'The record type to replace'
    required: true
  value:
    description: 'The new value for the subdomain/record type combo'
    required: true
  token:
    description: 'The Vercel authentication token'
    required: true
  team-name:
    description: 'The name of the team that controls the domain, e.g. Uniswap'
    required: true
runs:
  using: 'node12'
  main: 'index.js'