name: Crowdin

on:
  push:
    branches:
      - main

  # manual trigger
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    name: Synchronize with Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Synchronize
        uses: crowdin/github-action@1.1.0
        with:
          upload_sources: true
          download_translations: true
          project_id: 458284
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN_SECRET }}
          source: 'src/locales/en-US.po'
          translation: 'src/locales/%locale%.po'
          pull_request_title: "chore(i18n): synchronize translations from Crowdin"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
